import {
  APP_PERMISSIONS,
  APP_ROLES,
  type AppPermission,
  type AppRole,
} from "./types";

const allPermissions = Object.values(APP_PERMISSIONS) as AppPermission[];

export const rolePermissionMatrix: Record<AppRole, AppPermission[]> = {
  [APP_ROLES.PlatformAdmin]: allPermissions,
  [APP_ROLES.OrganizationAdmin]: [
    APP_PERMISSIONS.DashboardView,
    APP_PERMISSIONS.OrganizationView,
    APP_PERMISSIONS.OrganizationManage,
    APP_PERMISSIONS.CondominiumView,
    APP_PERMISSIONS.CondominiumManage,
    APP_PERMISSIONS.StructureView,
    APP_PERMISSIONS.StructureManage,
    APP_PERMISSIONS.UnitView,
    APP_PERMISSIONS.UnitManage,
    APP_PERMISSIONS.ResidentView,
    APP_PERMISSIONS.ResidentManage,
    APP_PERMISSIONS.ProfileView,
    APP_PERMISSIONS.ProfileManage,
    APP_PERMISSIONS.FinancialView,
    APP_PERMISSIONS.FinancialManage,
    APP_PERMISSIONS.GatehouseView,
    APP_PERMISSIONS.GatehouseManage,
    APP_PERMISSIONS.VehicleView,
    APP_PERMISSIONS.VehicleManage,
    APP_PERMISSIONS.DeliveryView,
    APP_PERMISSIONS.DeliveryManage,
    APP_PERMISSIONS.ReservationView,
    APP_PERMISSIONS.ReservationManage,
    APP_PERMISSIONS.PendingView,
    APP_PERMISSIONS.EnvironmentSwitch,
  ],
  [APP_ROLES.Syndic]: [
    APP_PERMISSIONS.DashboardView,
    APP_PERMISSIONS.CondominiumView,
    APP_PERMISSIONS.CondominiumManage,
    APP_PERMISSIONS.StructureView,
    APP_PERMISSIONS.StructureManage,
    APP_PERMISSIONS.UnitView,
    APP_PERMISSIONS.UnitManage,
    APP_PERMISSIONS.ResidentView,
    APP_PERMISSIONS.ResidentManage,
    APP_PERMISSIONS.ProfileView,
    APP_PERMISSIONS.FinancialView,
    APP_PERMISSIONS.FinancialManage,
    APP_PERMISSIONS.GatehouseView,
    APP_PERMISSIONS.GatehouseManage,
    APP_PERMISSIONS.VehicleView,
    APP_PERMISSIONS.VehicleManage,
    APP_PERMISSIONS.DeliveryView,
    APP_PERMISSIONS.DeliveryManage,
    APP_PERMISSIONS.ReservationView,
    APP_PERMISSIONS.ReservationManage,
    APP_PERMISSIONS.PendingView,
    APP_PERMISSIONS.EnvironmentSwitch,
  ],
  [APP_ROLES.SubSyndic]: [
    APP_PERMISSIONS.DashboardView,
    APP_PERMISSIONS.CondominiumView,
    APP_PERMISSIONS.StructureView,
    APP_PERMISSIONS.UnitView,
    APP_PERMISSIONS.ResidentView,
    APP_PERMISSIONS.ProfileView,
    APP_PERMISSIONS.FinancialView,
    APP_PERMISSIONS.GatehouseView,
    APP_PERMISSIONS.VehicleView,
    APP_PERMISSIONS.DeliveryView,
    APP_PERMISSIONS.ReservationView,
    APP_PERMISSIONS.PendingView,
    APP_PERMISSIONS.EnvironmentSwitch,
  ],
  [APP_ROLES.Counselor]: [
    APP_PERMISSIONS.DashboardView,
    APP_PERMISSIONS.CondominiumView,
    APP_PERMISSIONS.UnitView,
    APP_PERMISSIONS.ResidentView,
    APP_PERMISSIONS.FinancialView,
    APP_PERMISSIONS.PendingView,
    APP_PERMISSIONS.EnvironmentSwitch,
  ],
  [APP_ROLES.Gatehouse]: [
    APP_PERMISSIONS.DashboardView,
    APP_PERMISSIONS.GatehouseView,
    APP_PERMISSIONS.GatehouseManage,
    APP_PERMISSIONS.VehicleView,
    APP_PERMISSIONS.DeliveryView,
    APP_PERMISSIONS.DeliveryManage,
    APP_PERMISSIONS.PendingView,
    APP_PERMISSIONS.EnvironmentSwitch,
  ],
  [APP_ROLES.Resident]: [
    APP_PERMISSIONS.DashboardView,
    APP_PERMISSIONS.CondominiumView,
    APP_PERMISSIONS.ReservationView,
    APP_PERMISSIONS.ReservationManage,
    APP_PERMISSIONS.VehicleView,
    APP_PERMISSIONS.PendingView,
    APP_PERMISSIONS.EnvironmentSwitch,
  ],
  [APP_ROLES.Collaborator]: [
    APP_PERMISSIONS.DashboardView,
    APP_PERMISSIONS.PendingView,
    APP_PERMISSIONS.EnvironmentSwitch,
  ],
  [APP_ROLES.Financial]: [
    APP_PERMISSIONS.DashboardView,
    APP_PERMISSIONS.CondominiumView,
    APP_PERMISSIONS.UnitView,
    APP_PERMISSIONS.ResidentView,
    APP_PERMISSIONS.FinancialView,
    APP_PERMISSIONS.FinancialManage,
    APP_PERMISSIONS.PendingView,
    APP_PERMISSIONS.EnvironmentSwitch,
  ],
  [APP_ROLES.Auditor]: [
    APP_PERMISSIONS.DashboardView,
    APP_PERMISSIONS.OrganizationView,
    APP_PERMISSIONS.CondominiumView,
    APP_PERMISSIONS.StructureView,
    APP_PERMISSIONS.UnitView,
    APP_PERMISSIONS.ResidentView,
    APP_PERMISSIONS.ProfileView,
    APP_PERMISSIONS.FinancialView,
    APP_PERMISSIONS.GatehouseView,
    APP_PERMISSIONS.VehicleView,
    APP_PERMISSIONS.DeliveryView,
    APP_PERMISSIONS.ReservationView,
    APP_PERMISSIONS.PendingView,
    APP_PERMISSIONS.AuditView,
    APP_PERMISSIONS.ComplianceView,
    APP_PERMISSIONS.EnvironmentSwitch,
  ],
};
